name: Link check
on:
  push:
    paths: ["**/*.md"]
  pull_request:
    paths: ["**/*.md"]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail "**/*.md"
